// <auto-generated />
namespace StudentsMine.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class HW_Projects_Rel2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HW_Projects_Rel2));
        
        string IMigrationMetadata.Id
        {
            get { return "201801241615041_HW_Projects_Rel2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
